_wandb:
    value:
        cli_version: 0.23.1
        e:
            n2y7s5lin4o2cwud1r1vt50l2d7sfhvq:
                codePath: d:\Chula\2110573-PATT-RECOG\05_PyTorch\HW5_Precipitation_Nowcasting_PyTorch_Student_2026.ipynb
                codePathLocal: HW5_Precipitation_Nowcasting_PyTorch_Student_2026.ipynb
                cpu_count: 10
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1000203087872"
                        used: "100102979584"
                email: chyut2005@gmail.com
                executable: c:\Users\Faith\miniconda3\envs\pattern\python.exe
                git:
                    commit: 943286eeeafa4f3e3f5d1e3233c67da97460c152
                    remote: https://github.com/faith-cr/2110573-PATT-RECOG.git
                gpu: NVIDIA GeForce RTX 5060
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 3840
                      memoryTotal: "8546942976"
                      name: NVIDIA GeForce RTX 5060
                      uuid: GPU-ff7ad87d-aebd-9652-110b-b781441d25a2
                host: faith
                memory:
                    total: "34115457024"
                os: Windows-10-10.0.26100-SP0
                program: d:\Chula\2110573-PATT-RECOG\05_PyTorch\HW5_Precipitation_Nowcasting_PyTorch_Student_2026.ipynb
                python: CPython 3.10.19
                root: d:\Chula\2110573-PATT-RECOG\05_PyTorch
                startedAt: "2026-02-14T15:12:00.071535Z"
                writerId: n2y7s5lin4o2cwud1r1vt50l2d7sfhvq
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
            "3":
                - 1
                - 2
                - 16
            "4": 3.10.19
            "5": 0.23.1
            "8":
                - 1
                - 3
            "10":
                - 20
            "12": 0.23.1
            "13": windows-amd64
architecture:
    value: ConvTransformer
epochs:
    value: 70
hidden_size:
    value: 128
lr:
    value: 0.001
scheduler_factor:
    value: 0.5
scheduler_min_lr:
    value: 1e-06
scheduler_patience:
    value: 2
seq_len:
    value: 5
